package tlscert

import (
	"crypto/tls"
	"crypto/x509"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestLoad_AutoGenerated(t *testing.T) {
	cfg, err := Load(Config{Hostnames: []string{"localhost", "127.0.0.1"}})
	require.NoError(t, err)
	require.NotNil(t, cfg)
	require.Len(t, cfg.Certificates, 1)

	leaf, err := x509.ParseCertificate(cfg.Certificates[0].Certificate[0])
	require.NoError(t, err)
	assert.Contains(t, leaf.DNSNames, "localhost")
}

func TestLoad_FromFiles(t *testing.T) {
	// Use auto-gen, write it to disk, then load it back.
	gen, err := generateSelfSigned([]string{"localhost"})
	require.NoError(t, err)

	dir := t.TempDir()
	certPath := filepath.Join(dir, "tls.crt")
	keyPath := filepath.Join(dir, "tls.key")

	require.NoError(t, os.WriteFile(certPath, gen.certPEM, 0o644))
	require.NoError(t, os.WriteFile(keyPath, gen.keyPEM, 0o600))

	cfg, err := Load(Config{CertFile: certPath, KeyFile: keyPath})
	require.NoError(t, err)
	require.NotNil(t, cfg)
	require.Len(t, cfg.Certificates, 1)
	assert.Equal(t, tls.VersionTLS12, int(cfg.MinVersion))
}
